version: '3.8'

services:
  # MongoDB Datenbank
  mongodb:
    image: mongo:6.0
    container_name: kretschmer-drop-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "username"
      MONGO_INITDB_ROOT_PASSWORD: "password"
      MONGO_INITDB_DATABASE: kretschmer-drop
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - kretschmer-drop-network

  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: kretschmer-drop-server
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://username:password@mongodb:27017/kretschmer-drop?authSource=username
      JWT_SECRET: kretschmer-drop-super-secret-jwt-key-2025
      PORT: 5000
      NODE_ENV: development
    ports:
      - "10031:5000"
    volumes:
      - ./server/uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - kretschmer-drop-network

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: kretschmer-drop-client
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://server:5000
      DANGEROUSLY_DISABLE_HOST_CHECK: "true"
      WDS_SOCKET_HOST: "0.0.0.0"
      WDS_SOCKET_PORT: "3000"
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "10030:3000"
    depends_on:
      - server
    networks:
      - kretschmer-drop-network

volumes:
  mongodb_data:
    driver: local

networks:
  kretschmer-drop-network:
    driver: bridge
